version: "3.9"
services:
  streaks-runner:
    build: .
    container_name: "streaks-runner"
    restart: always
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./config.yml:/runner/config.yml
      - ./log:/runner/log
