version: "3.9"
services:
  streaks-cli:
    image: "registry.chevro.fr/streaks/cli:latest"
    container_name: "streaks-cli"
    restart: always
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./config.yml:/cli/config.yml
      - ./.env:/cli/.env
